export const items = [{id:"1",title:"Boiled Egg" ,
descripition:"Healhy Breakfast Toast With Avocado, Boiled Egg On Wooden Cutting Board",
img:"img1.jpg",category:"Breakfast",price:"50 pounds"},{id:"2",title:"Bacon" ,
descripition:"A delicous home style breakfast with crispy bacon, eggs, pancakes, toast, coffee, and orange juice",
img:"img2.jpg",category:"Breakfast",price:"70 pounds"},{id:"3",title:"bacon and toast" ,
descripition:"traditional full american breakfast eggs pancakes with bacon and toast",
img:"img3.jpg",category:"Lunch",price:"40 pounds"},{id:"4",title:"Vegan super sandwich" ,
descripition:"Vegetarian sandwich made with sourdough bread, avocado creme, cucumber, radish and remoulade sauce with bowl of sprouts served on a table.",
img:"img4.jpg",category:"Lunch",price:"100 pounds"},{id:"5",title:"Avocado toast" ,
descripition:"Avocado toast with fried mushrooms garnished with microgreen",
img:"img5.jpg",category:"Lunch",price:"120 pounds"},{id:"6",title:"hot dogs" ,
descripition:"hot dogs with puff pastry with bell peppers, cheese and olives and basil of the catering table",
img:"img6.jpg",category:"Lunch",price:"150 pounds"},{id:"7",title:"Doner Kebab|Dinner" ,
descripition:"Barbecue, chicken, Bread, Dinner, Doner Kebab",
img:"img7.jpg",category:"Dinner",price:"200 pounds"},{id:"8",title:"Turkish pizza pide" ,
descripition:"Traditional turkish baked dish pide. Turkish pizza pide, Middle eastern appetizers. Turkish cuisine. Top view. Pide with meat filling.",
img:"img8.jpg",category:"Dinner",price:"280 pounds"}]